require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/brand_ecus", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BrandEcu. As you add validations to BrandEcu, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BrandEcu.create! valid_attributes
      get brand_ecus_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      brand_ecu = BrandEcu.create! valid_attributes
      get brand_ecu_url(brand_ecu)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_brand_ecu_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      brand_ecu = BrandEcu.create! valid_attributes
      get edit_brand_ecu_url(brand_ecu)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BrandEcu" do
        expect {
          post brand_ecus_url, params: { brand_ecu: valid_attributes }
        }.to change(BrandEcu, :count).by(1)
      end

      it "redirects to the created brand_ecu" do
        post brand_ecus_url, params: { brand_ecu: valid_attributes }
        expect(response).to redirect_to(brand_ecu_url(BrandEcu.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BrandEcu" do
        expect {
          post brand_ecus_url, params: { brand_ecu: invalid_attributes }
        }.to change(BrandEcu, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post brand_ecus_url, params: { brand_ecu: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested brand_ecu" do
        brand_ecu = BrandEcu.create! valid_attributes
        patch brand_ecu_url(brand_ecu), params: { brand_ecu: new_attributes }
        brand_ecu.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the brand_ecu" do
        brand_ecu = BrandEcu.create! valid_attributes
        patch brand_ecu_url(brand_ecu), params: { brand_ecu: new_attributes }
        brand_ecu.reload
        expect(response).to redirect_to(brand_ecu_url(brand_ecu))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        brand_ecu = BrandEcu.create! valid_attributes
        patch brand_ecu_url(brand_ecu), params: { brand_ecu: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested brand_ecu" do
      brand_ecu = BrandEcu.create! valid_attributes
      expect {
        delete brand_ecu_url(brand_ecu)
      }.to change(BrandEcu, :count).by(-1)
    end

    it "redirects to the brand_ecus list" do
      brand_ecu = BrandEcu.create! valid_attributes
      delete brand_ecu_url(brand_ecu)
      expect(response).to redirect_to(brand_ecus_url)
    end
  end
end
