# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Ecm.destroy_all
Car.destroy_all
Model.destroy_all
Make.destroy_all

Ecm.create(name: 'Delphi AcDelco E37')
Ecm.create(name: 'Delphi AcDelco E38')
Ecm.create(name: 'Delphi AcDelco E39_E39a')
Ecm.create(name: 'Delphi AcDelco E69')
Ecm.create(name: 'Delphi AcDelco E78')
Ecm.create(name: 'Delphi AcDelco E83')
Ecm.create(name: 'Delphi MT20')
Ecm.create(name: 'Delphi MT21_22')
Ecm.create(name: 'Delphi MT60')
Ecm.create(name: 'Delphi MT80')
Ecm.create(name: 'Delphi MT92 GDI')
Ecm.create(name: 'Delphi MP140_MP240')
Ecm.create(name: 'Bosch M1.5.4')
Ecm.create(name: 'Bosch M7.0')
Ecm.create(name: 'Bosch M7.4.4')
Ecm.create(name: 'Bosch M7.4.5')
Ecm.create(name: 'Bosch M7.9.7')
Ecm.create(name: 'Bosch M7.9.7+')
Ecm.create(name: 'KEFICO (Bosch M7.9.7)')
Ecm.create(name: 'KEFICO (Bosch M7.9.7+)')
Ecm.create(name: 'Bosch M7.8')
Ecm.create(name: 'Bosch M7.8.8')
Ecm.create(name: 'Bosch M17.9.1')
Ecm.create(name: 'Bosch M17.9.2')
Ecm.create(name: 'Bosch M17.9.7')
Ecm.create(name: 'Bosch M17.9.7.1')
Ecm.create(name: 'Bosch M17.9.11')
Ecm.create(name: 'Bosch M17.5')
Ecm.create(name: 'Bosch M17.5.5')
Ecm.create(name: 'Bosch MEVD17.2.7 BMW')
Ecm.create(name: 'Bosch MEVD17.2.2 BMW')
Ecm.create(name: 'Bosch MEV17.4.2 PSA')
Ecm.create(name: 'Bosch MEV17.4.6 BMW')
Ecm.create(name: 'Bosch MEV17.2.2 BMW')
Ecm.create(name: 'Bosch MEG17.9.21 HK')
Ecm.create(name: 'Bosch MEG17.9.2 HK')
Ecm.create(name: 'Bosch MEDG17.9.8 HK')
Ecm.create(name: 'Bosch MED9.6.1 GM (E69)')
Ecm.create(name: 'Bosch MED9.5.10 VAG')
Ecm.create(name: 'Bosch MED9.1.x VAG')
Ecm.create(name: 'Bosch MED9.1 VAG')
Ecm.create(name: 'Bosch MED17.9.8 HK')
Ecm.create(name: 'Bosch MED17.9.63 SUZUKI')
Ecm.create(name: 'Bosch MED17.5.5 VAG')
Ecm.create(name: 'Bosch MED17.5.25 VAG')
Ecm.create(name: 'Bosch MED17.5.21 VAG')
Ecm.create(name: 'Bosch MED17.5.2 VAG')
Ecm.create(name: 'Bosch MED17.5.21 VAG')
Ecm.create(name: 'Denso')
Ecm.create(name: 'Denso Toyota')
Ecm.create(name: 'Denso Jaguar')
Ecm.create(name: 'Denso Mazda')
Ecm.create(name: 'Mitsubishi')
Ecm.create(name: 'Ford Visteon ESU 131_411_418')
Ecm.create(name: 'Ford Sim28_Sim29')
Ecm.create(name: 'Siemens Simtec 70')
Ecm.create(name: 'Siemens Simtec 71')
Ecm.create(name: 'Siemens Simtec 75')
Ecm.create(name: 'Siemens Simtec 76')
Ecm.create(name: 'Siemens Simtec 81')
Ecm.create(name: 'Siemens MSE3.5')
Ecm.create(name: 'SIM2K-24x (SIM2K-241/242/245)')
Ecm.create(name: 'SIM2K-25x (SIM2K-250/251/253)')
Ecm.create(name: 'Siemens SIM2K-141_341')
Ecm.create(name: 'Siemens SIMK41_43')
Ecm.create(name: 'GM ISFI-2S')
Ecm.create(name: 'GM ITMS-6F')
Ecm.create(name: 'GM EFI-4')
Ecm.create(name: 'Январь 5.1_5.1.1_5.1.2')
Ecm.create(name: 'Январь 7.2')
Ecm.create(name: 'Микас 10.3')
Ecm.create(name: 'Микас 11')
Ecm.create(name: 'Микас 12')
Ecm.create(name: 'М74')
Ecm.create(name: 'М75')
Ecm.create(name: 'М86')
Ecm.create(name: 'VS5.1')
Ecm.create(name: 'VS9.2')
Ecm.create(name: 'Magneti Marelli 4HV')
Ecm.create(name: 'Magneti Marelli 7GV')
Ecm.create(name: 'Simos 12')
Ecm.create(name: 'Valeo V42')
Ecm.create(name: 'Sirius D3_4')
Ecm.create(name: 'Sirius D32_42')
Ecm.create(name: 'Continental EMS3125')
Ecm.create(name: 'Continental EMS3132')
Ecm.create(name: 'Continental EMS3120')
Ecm.create(name: 'Continental EMS3130')

make = Make.create(name: 'AUDI')
Model.create(make: make, name: 'A3')
Model.create(make: make, name: 'A4')
Model.create(make: make, name: 'A5')
Model.create(make: make, name: 'A6')
Model.create(make: make, name: 'A7')
Model.create(make: make, name: 'A8')
Model.create(make: make, name: 'S3')
Model.create(make: make, name: 'S6')
Model.create(make: make, name: 'S8')
Model.create(make: make, name: 'SQ5')
Model.create(make: make, name: 'Q3')
Model.create(make: make, name: 'Q5')
Model.create(make: make, name: 'Q7')
Model.create(make: make, name: 'E-TRON')
Model.create(make: make, name: 'RS3')
Model.create(make: make, name: 'RS4')
Model.create(make: make, name: 'RS5')
Model.create(make: make, name: 'RS6')
Model.create(make: make, name: 'RS7')
Model.create(make: make, name: 'RSQ8')

make = Make.create(name: 'ACURA')
Model.create(make: make, name: 'MDX')
Model.create(make: make, name: 'RDX')
Model.create(make: make, name: 'CDX')

make = Make.create(name: 'BMW')
Model.create(make: make, name: 'Ex 1')
Model.create(make: make, name: 'Fx 1')
Model.create(make: make, name: 'Fx 2')
Model.create(make: make, name: 'Ex 3')
Model.create(make: make, name: 'Fx 3')
Model.create(make: make, name: 'Gx 3')
Model.create(make: make, name: 'Fx 4')
Model.create(make: make, name: 'Ex 5')
Model.create(make: make, name: 'Fx 5')
Model.create(make: make, name: 'Gx 5')
Model.create(make: make, name: 'Ex 6')
Model.create(make: make, name: 'Fx 6')
Model.create(make: make, name: 'Gx 6')
Model.create(make: make, name: 'Ex 7')
Model.create(make: make, name: 'Fx 7')
Model.create(make: make, name: 'Gx 7')
Model.create(make: make, name: 'MINI')
Model.create(make: make, name: 'I3')
Model.create(make: make, name: 'I8')
Model.create(make: make, name: 'IX')
Model.create(make: make, name: 'Ex X1')
Model.create(make: make, name: 'Fx X1')
Model.create(make: make, name: 'Fx X2')
Model.create(make: make, name: 'Ex X3')
Model.create(make: make, name: 'Fx X3')
Model.create(make: make, name: 'Gx X3')
Model.create(make: make, name: 'Fx X4')
Model.create(make: make, name: 'Gx X4')
Model.create(make: make, name: 'Ex X5')
Model.create(make: make, name: 'Fx X5')
Model.create(make: make, name: 'Gx X5')
Model.create(make: make, name: 'Ex X6')
Model.create(make: make, name: 'Fx X6')
Model.create(make: make, name: 'Gx X6')
Model.create(make: make, name: 'Gx X7')
Model.create(make: make, name: 'Ex Z4')
Model.create(make: make, name: 'Gx Z4')

make = Make.create(name: 'CHEVROLET')
Model.create(make: make, name: 'AVEO')
Model.create(make: make, name: 'CRUZE')
Model.create(make: make, name: 'CAPTIVA')
Model.create(make: make, name: 'COBALT')
Model.create(make: make, name: 'SPARK')
Model.create(make: make, name: 'ORLANDO')
Model.create(make: make, name: 'LACHETTI')
Model.create(make: make, name: 'LANOS')
Model.create(make: make, name: 'EPICA')
Model.create(make: make, name: 'VOLT')
Model.create(make: make, name: 'BOLT')
Model.create(make: make, name: 'TAHOE')
Model.create(make: make, name: 'COMARO')

make = Make.create(name: 'CHERY')
Model.create(make: make, name: 'AMULET')
Model.create(make: make, name: 'ARRIZO')
Model.create(make: make, name: 'BONUS')
Model.create(make: make, name: 'EASTAR')
Model.create(make: make, name: 'TIGO')
Model.create(make: make, name: 'TIGO 2')
Model.create(make: make, name: 'TIGO 3')
Model.create(make: make, name: 'TIGO 4')
Model.create(make: make, name: 'TIGO 5')
Model.create(make: make, name: 'TIGO 7')
Model.create(make: make, name: 'TIGO 8')
Model.create(make: make, name: 'KIMO')
Model.create(make: make, name: 'QQ')
Model.create(make: make, name: 'QQ 6')
Model.create(make: make, name: 'FORA')
Model.create(make: make, name: 'VERY')
Model.create(make: make, name: 'INDIS')

make = Make.create(name: 'CITROEN')
Model.create(make: make, name: 'C1')
Model.create(make: make, name: 'C3')
Model.create(make: make, name: 'C4')
Model.create(make: make, name: 'C6')
Model.create(make: make, name: 'C-Elysée')
Model.create(make: make, name: 'C5')
Model.create(make: make, name: 'BERLINGO')
Model.create(make: make, name: 'JUMPY')
Model.create(make: make, name: 'JUMPER')

make = Make.create(name: 'DAEWOO')
Model.create(make: make, name: 'NEXIA')
Model.create(make: make, name: 'MATIZ')
Model.create(make: make, name: 'GENTRA')

make = Make.create(name: 'DAIHATSU')
Model.create(make: make, name: 'TREVIS')

make = Make.create(name: 'VAZ')
Model.create(make: make, name: '2107')
Model.create(make: make, name: '2109')
Model.create(make: make, name: '2110')
Model.create(make: make, name: '2111')
Model.create(make: make, name: '2112')
Model.create(make: make, name: '2114')
Model.create(make: make, name: '2115')
Model.create(make: make, name: 'GRANTA')
Model.create(make: make, name: 'KALINA')
Model.create(make: make, name: 'PRIORA')
Model.create(make: make, name: 'VESTA')
Model.create(make: make, name: 'XRAY')
Model.create(make: make, name: 'LARGUS')
Model.create(make: make, name: 'NIVA')
Model.create(make: make, name: 'CHEVROLET NIVA')

make = Make.create(name: 'GAZ')
Model.create(make: make, name: 'GAZEL')

make = Make.create(name: 'UAZ')
Model.create(make: make, name: 'FERMER')
Model.create(make: make, name: 'PATRIOT')
Model.create(make: make, name: 'БУХАНКА')

make = Make.create(name: 'ZAZ')
Model.create(make: make, name: 'CHANCE')
Model.create(make: make, name: 'VIDA')

make = Make.create(name: 'FIAT')
Model.create(make: make, name: 'ALBEA')

make = Make.create(name: 'FORD')
Model.create(make: make, name: 'FOCUS')
Model.create(make: make, name: 'FOCUS 2')
Model.create(make: make, name: 'FOCUS 3')
Model.create(make: make, name: 'FOCUS 4')
Model.create(make: make, name: 'CMAX')
Model.create(make: make, name: 'ECOSPORT')
Model.create(make: make, name: 'EXPLORER')
Model.create(make: make, name: 'FUSION')
Model.create(make: make, name: 'KUGA')
Model.create(make: make, name: 'KUGA 2')
Model.create(make: make, name: 'MONDEO')
Model.create(make: make, name: 'MONDEO 2')
Model.create(make: make, name: 'MONDEO 3')
Model.create(make: make, name: 'MONDEO 4')
Model.create(make: make, name: 'TRANSIT')

make = Make.create(name: 'GEELE')
Model.create(make: make, name: 'TUGELLA')
Model.create(make: make, name: 'ATLAS')
Model.create(make: make, name: 'COOLRAY')
Model.create(make: make, name: 'EMGRAND')

make = Make.create(name: 'GREAT WALL')
Model.create(make: make, name: 'HOVER H2')
Model.create(make: make, name: 'HOVER H3')
Model.create(make: make, name: 'HOVER H4')
Model.create(make: make, name: 'HOVER H5')
Model.create(make: make, name: 'SAFE')
Model.create(make: make, name: 'POER')

make = Make.create(name: 'HAVAL')
Model.create(make: make, name: 'JOLION')
Model.create(make: make, name: 'DARGO')
Model.create(make: make, name: 'H2')
Model.create(make: make, name: 'H6')
Model.create(make: make, name: 'H8')
Model.create(make: make, name: 'COUPE C')
Model.create(make: make, name: 'F7')
Model.create(make: make, name: 'H9')

make = Make.create(name: 'HONDA')
Model.create(make: make, name: 'ACCORD')
Model.create(make: make, name: 'CRV')
Model.create(make: make, name: 'HRV')
Model.create(make: make, name: 'PILOT')
Model.create(make: make, name: 'CIVIC')

make = Make.create(name: 'HYUNDAI')
Model.create(make: make, name: 'ACCENT')
Model.create(make: make, name: 'GETZ')
Model.create(make: make, name: 'I10')
Model.create(make: make, name: 'I20')
Model.create(make: make, name: 'I30')
Model.create(make: make, name: 'I40')
Model.create(make: make, name: 'AURA')
Model.create(make: make, name: 'CELESTA')
Model.create(make: make, name: 'ELANTRA')
Model.create(make: make, name: 'GRANDEUR')
Model.create(make: make, name: 'HB20')
Model.create(make: make, name: 'SOLARIS')
Model.create(make: make, name: 'IONIQ')
Model.create(make: make, name: 'SONATA')
Model.create(make: make, name: 'XCENT')
Model.create(make: make, name: 'CRETA')
Model.create(make: make, name: 'TUCSON')
Model.create(make: make, name: 'IX35')
Model.create(make: make, name: 'KONA')
Model.create(make: make, name: 'PALISADE')
Model.create(make: make, name: 'SANTA FE')
Model.create(make: make, name: 'VENUE')
Model.create(make: make, name: 'STAREX')
Model.create(make: make, name: 'VELOSTER')
Model.create(make: make, name: 'GENESIS')

make = Make.create(name: 'INFINITI')
Model.create(make: make, name: 'Q30')
Model.create(make: make, name: 'Q50')
Model.create(make: make, name: 'Q60')
Model.create(make: make, name: 'Q70')
Model.create(make: make, name: 'QX30')
Model.create(make: make, name: 'QX50')
Model.create(make: make, name: 'QX55')
Model.create(make: make, name: 'QX60')
Model.create(make: make, name: 'QX70')
Model.create(make: make, name: 'QX80')
Model.create(make: make, name: 'G25')
Model.create(make: make, name: 'ESQ')

make = Make.create(name: 'JAGUAR')
Model.create(make: make, name: 'XF 3.0')

make = Make.create(name: 'KIA')
Model.create(make: make, name: 'RIO')
Model.create(make: make, name: 'CEED')
Model.create(make: make, name: 'SPORTAGE')
Model.create(make: make, name: 'SORENTO')
Model.create(make: make, name: 'CERATO')
Model.create(make: make, name: 'PICANTO')
Model.create(make: make, name: 'FORTE')
Model.create(make: make, name: 'OPTIMA')
Model.create(make: make, name: 'MOHAVE')
Model.create(make: make, name: 'SOUL')
Model.create(make: make, name: 'K4')
Model.create(make: make, name: 'K5')
Model.create(make: make, name: 'K7')
Model.create(make: make, name: 'K8')
Model.create(make: make, name: 'K9')
Model.create(make: make, name: 'PEGAS')
Model.create(make: make, name: 'NIRO')
Model.create(make: make, name: 'SELTOS')
Model.create(make: make, name: 'CARENS')
Model.create(make: make, name: 'CARNIVAL')
Model.create(make: make, name: 'KX5')
Model.create(make: make, name: 'EV6')

make = Make.create(name: 'LEXUS')
Model.create(make: make, name: 'CT')
Model.create(make: make, name: 'IS')
Model.create(make: make, name: 'ES')
Model.create(make: make, name: 'LS')
Model.create(make: make, name: 'LC')
Model.create(make: make, name: 'RC')
Model.create(make: make, name: 'UX')
Model.create(make: make, name: 'NX')
Model.create(make: make, name: 'RX')
Model.create(make: make, name: 'RZ')
Model.create(make: make, name: 'GX')
Model.create(make: make, name: 'RX')
Model.create(make: make, name: 'RM')

make = Make.create(name: 'LIFAN')
Model.create(make: make, name: 'SOLANO')
Model.create(make: make, name: 'X50')
Model.create(make: make, name: 'X60')
Model.create(make: make, name: 'X70')

make = Make.create(name: 'MAZDA')
Model.create(make: make, name: 'MAZDA 2')
Model.create(make: make, name: 'MAZDA 3')
Model.create(make: make, name: 'MAZDA 5')
Model.create(make: make, name: 'MAZDA 6')
Model.create(make: make, name: 'MAZDA CX3')
Model.create(make: make, name: 'MAZDA CX5')
Model.create(make: make, name: 'MAZDA CX7')
Model.create(make: make, name: 'MAZDA CX8')
Model.create(make: make, name: 'MAZDA CX9')
Model.create(make: make, name: 'MAZDA BT50')
Model.create(make: make, name: 'MAZDA MX30')
Model.create(make: make, name: 'MAZDA MX5')
Model.create(make: make, name: 'MAZDA CX60')

make = Make.create(name: 'MERCEDES-BENZ')
Model.create(make: make, name: 'GLK')

make = Make.create(name: 'MITSUBISHI')
Model.create(make: make, name: 'LANCER 9')
Model.create(make: make, name: 'LANCER 10')
Model.create(make: make, name: 'ASX')
Model.create(make: make, name: 'OUTLANDER')
Model.create(make: make, name: 'PAJERO')
Model.create(make: make, name: 'PAJERO SPORT')

make = Make.create(name: 'NISSAN')
Model.create(make: make, name: 'ALMERA')
Model.create(make: make, name: 'ALMERA CLASSIC')
Model.create(make: make, name: 'NOTE')
Model.create(make: make, name: 'TIIDA')
Model.create(make: make, name: 'JUKE')
Model.create(make: make, name: 'MURANO')
Model.create(make: make, name: 'PATHFINDER')
Model.create(make: make, name: 'QASHQAI')
Model.create(make: make, name: 'X-TRAL')
Model.create(make: make, name: 'TERRANO')
Model.create(make: make, name: 'LEAF')

make = Make.create(name: 'OPEL')
Model.create(make: make, name: 'ASTRA G')
Model.create(make: make, name: 'ASTRA H')
Model.create(make: make, name: 'ASTRA J')
Model.create(make: make, name: 'ANTARA')
Model.create(make: make, name: 'MERIVA')
Model.create(make: make, name: 'CORSA')
Model.create(make: make, name: 'ISIGNIA')
Model.create(make: make, name: 'MOKKA')
Model.create(make: make, name: 'VECTRA')
Model.create(make: make, name: 'ZAFIRA')

make = Make.create(name: 'PEUGEOT')
Model.create(make: make, name: '107')
Model.create(make: make, name: '1007')
Model.create(make: make, name: '108')
Model.create(make: make, name: '206')
Model.create(make: make, name: '207')
Model.create(make: make, name: '208')
Model.create(make: make, name: '2008')
Model.create(make: make, name: '301')
Model.create(make: make, name: '308')
Model.create(make: make, name: '3008')
Model.create(make: make, name: '307')
Model.create(make: make, name: '407')
Model.create(make: make, name: '408')
Model.create(make: make, name: '4008')
Model.create(make: make, name: 'PARTNER')
Model.create(make: make, name: 'EXPERT')
Model.create(make: make, name: 'BOXER')

make = Make.create(name: 'RAVON')
Model.create(make: make, name: 'R2')
Model.create(make: make, name: 'R3')
Model.create(make: make, name: 'R4')

make = Make.create(name: 'RENAULT')
Model.create(make: make, name: 'ARKANA')
Model.create(make: make, name: 'LOGAN')
Model.create(make: make, name: 'MEGAN')
Model.create(make: make, name: 'DUSTER')
Model.create(make: make, name: 'SANDERO')
Model.create(make: make, name: 'FLUENS')
Model.create(make: make, name: 'SCENIC')
Model.create(make: make, name: 'SIMBOL')
Model.create(make: make, name: 'CLIO')
Model.create(make: make, name: 'KAPTUR')
Model.create(make: make, name: 'CALEOS')
Model.create(make: make, name: 'LAGUNA')
Model.create(make: make, name: 'KANGOO')

make = Make.create(name: 'ROVER')
Model.create(make: make, name: 'DISCAVERY')
Model.create(make: make, name: 'FREELANDER')
Model.create(make: make, name: 'RANGE ROVER')
Model.create(make: make, name: 'EVOQUE')

make = Make.create(name: 'SKODA')
Model.create(make: make, name: 'FABIA')
Model.create(make: make, name: 'KAROQ')
Model.create(make: make, name: 'OKTAVIA')
Model.create(make: make, name: 'RAPID')
Model.create(make: make, name: 'SUPERB')
Model.create(make: make, name: 'SCALA')
Model.create(make: make, name: 'KODIAQ')
Model.create(make: make, name: 'YETI')

make = Make.create(name: 'SSANGYONG')
Model.create(make: make, name: 'ACTYON')
Model.create(make: make, name: 'KYRON')
Model.create(make: make, name: 'REXTON')
Model.create(make: make, name: 'RODIUS')
Model.create(make: make, name: 'SIV EV')
Model.create(make: make, name: 'XLV')
Model.create(make: make, name: 'TIVOLI')

make = Make.create(name: 'SUZUKI')
Model.create(make: make, name: 'GRAND VITARA')
Model.create(make: make, name: 'IGNIS')
Model.create(make: make, name: 'LIANA')
Model.create(make: make, name: 'SWIFT')
Model.create(make: make, name: 'SX4')
Model.create(make: make, name: 'VITARA')
Model.create(make: make, name: 'XL7')

make = Make.create(name: 'TOYOTA')
Model.create(make: make, name: 'AURIS')
Model.create(make: make, name: 'AVENSIS')
Model.create(make: make, name: 'AVALON')
Model.create(make: make, name: 'CAMRY')
Model.create(make: make, name: 'LAND CRUISER')
Model.create(make: make, name: 'LAND CRUISER PRADO')
Model.create(make: make, name: 'HIGHLANDER')
Model.create(make: make, name: 'COROLLA')
Model.create(make: make, name: 'RAV4')
Model.create(make: make, name: 'PRIUS')
Model.create(make: make, name: 'YARIS')
Model.create(make: make, name: 'VENZA')

make = Make.create(name: 'VOLKSWAGEN')
Model.create(make: make, name: 'AMAROK')
Model.create(make: make, name: 'ATLAS')
Model.create(make: make, name: 'PASSAT')
Model.create(make: make, name: 'POLO')
Model.create(make: make, name: 'JETTA')
Model.create(make: make, name: 'CADDY')
Model.create(make: make, name: 'PASSAT CC')
Model.create(make: make, name: 'ID.3')
Model.create(make: make, name: 'ID.4')
Model.create(make: make, name: 'GOLF PLUS')
Model.create(make: make, name: 'GOLF R')

make = Make.create(name: 'VOLVO')
Model.create(make: make, name: 'C30')
Model.create(make: make, name: 'S40')
Model.create(make: make, name: 'V40')
Model.create(make: make, name: 'XC40')
Model.create(make: make, name: 'V50')
Model.create(make: make, name: 'S60')
Model.create(make: make, name: 'V60')
Model.create(make: make, name: 'XC60')
Model.create(make: make, name: 'C70')
Model.create(make: make, name: 'V70')
Model.create(make: make, name: 'XC70')
Model.create(make: make, name: 'S80')
Model.create(make: make, name: 'S90')
Model.create(make: make, name: 'V90')
Model.create(make: make, name: 'XC90')